### ISSUE TITLE
needs license

### ISSUE THREAD

**Issue by bixu** [bixu/pkgsrc#5]
In one specific case, DE regulations require me to ask for this or else copy the project to a private repo :(

**Comment by sax** [comment]
Would you like me to transfer this repo to you? I still have not built a real pipeline around using this, and I think you're more likely to do better upkeep of this cookbook than I will, at least in the near future.

**Comment by sax** [comment]
FYI I just added a license file with the MIT license, and pushed a new version to supermarket.

**Comment by bixu** [comment]
Thanks!

bixu.co

**Comment by bixu** [comment]
Oh - you're welcome to xfer ownership - I'd probably keep you as a collaborator of course

**Comment by sax** [comment]
done!

On Fri, Jul 24, 2015 at 1:03 AM, Blake Irvin notifications@github.com
wrote:

> Oh - you're welcome to xfer ownership - I'd probably keep you as a
> collaborator of course
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wanelo-chef/pkgsrc/issues/5#issuecomment-124414568.

## 

---

e s

**Comment by sax** [comment]
well, it seems like it'll take a while to transfer.

On Fri, Jul 24, 2015 at 10:49 AM, Eric Saxby sax@livinginthepast.org
wrote:

> done!
> 
> On Fri, Jul 24, 2015 at 1:03 AM, Blake Irvin notifications@github.com
> wrote:
> 
> > Oh - you're welcome to xfer ownership - I'd probably keep you as a
> > collaborator of course
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/wanelo-chef/pkgsrc/issues/5#issuecomment-124414568.
> 
> ## 
> 
> ---
> 
> e s

## 

---

e s

**Comment by bixu** [comment]
No rush!
